runtime: go115
handlers:
  # All URLs ending in .gif .png or .jpg are treated as paths to
  # static files in the static/ directory. The URL pattern is a
  # regular expression, with a grouping that is inserted into the
  # path to the file.
  - url: /(.*\.(gif|png|jpg|pdf))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|pdf)$